##########################
## User settable macros ##
##########################

Processor = 386

Compiler = wpp386

System = pmodew

Model = f

Include=.;$(%WATCOM)\h;include


Compiler_OptionsCPP = /bt=dos4g /d3 /5s /e10 /mf /w1 /fp5 /xs
#Compiler_OptionsCPP =  /5s /xs
Linker_options   = debug all option stack=128k option verbose

Exe_file     = fulcrum.exe

Object_files =                  fulcrum.obj &
                                gmvasm.obj &
                                gmvesa.obj &
                                gstrasm.obj &
                                gfxstrio.obj &
                                lw.obj &
                                m2camera.obj &
                                m2clip.obj &
                                m2dotpro.obj &
                                m2except.obj &
                                m2lookup.obj &
                                m2partic.obj &
                                m2pman.obj &
                                m2ppro.obj &
                                m2pt.obj &
                                m2pttr.obj &
                                m2ptf.obj &
                                m2ptftr.obj &
                                m2ptg.obj &
                                m2ptb.obj &
                                m2raw.obj &
                                m2render.obj &
                                m2serv.obj &
                                m2sort.obj &
                                m2vector.obj &
                                m2world.obj &
                                inimoove.obj &
                                rdtsc.obj &
                                timecntr.obj &
                                arj1.obj &
                                copro_s.obj &
                                m2read.obj &
                                m2tracks.obj &
                                fire.obj &
                                bfade.obj &
                                2dlink.obj &
                                2deye.obj &
                                2deffect.obj &
                                tracks.obj &
                                demo.obj &
                                mese.obj &
                                inimese.obj &
                                credits.obj &
                                inicred.obj &
                                picview.obj &
                                inierz.obj &
                                erz.obj &
                                vesa.obj &
                                vesac.obj &
                                rxm.obj &
                                awe.obj &
                                gus.obj &
                                sb.obj &
                                int.obj




####################
## Makefile rules ##
####################

$(Exe_file): $(Object_files)
             *wlink system $(System) $(Linker_options) name $(Exe_file) &
              file {$(Object_files)}

.asm.obj:
        tasm $< /m5 /zi /z /w2 /ml

.cpp.obj:
        wpp386  $(Compiler_OptionsCPP) -I$(Include) $<


